### ISSUE TITLE
Lidgren stuck on Client.Connect with no network adapters connected (Win8)

### ISSUE THREAD

**Issue by BinaryConstruct** [Indiefreaks/igf#5]
The lidgren client cannot connect to the server (as SinglePlayerSession) in the following cases:
Ip address is set to IPAddress.Loopback, IPAddress.Any when in Airplane mode or no network adapters are connected.

I have not been able to replicate this on Windows 7 dev environment, but I have on one non-dev machine. The sockets seem to bind find to 0.0.0.0:port, but the client messages never reach the server thread.

Upon further testing, it seems the client will connect if all network adapters are "disabled", but if any are enabled but not connected/plugged in the client will fail to connected even when IP address is any or loopback.

**Comment by BinaryConstruct** [comment]
Here is a workaround when setting up the sessionmanager.

``` csharp
            IPAddress mask;
            IPAddress myAddress = Lidgren.Network.NetUtility.GetMyAddress(out mask);
            if (myAddress != null && !myAddress.ToString().Contains("169.254."))
                SunBurn.AddManager(new LidgrenSessionManager(SunBurn));
            else
                SunBurn.AddManager(new LocalSessionManager(SunBurn));
```

**Comment by Indiefreaks** [comment]
I'll try to see with the Lidgren developer which options we have for such approach. Have you checked the firewall settings?

**Comment by BinaryConstruct** [comment]
Yes, I disabled the firewall just to be sure. It seems to only occur when the IP address of the NIC is 169.254._._

**Comment by Indiefreaks** [comment]
This 169.254._._ ip address pattern sounds to me like private local address (http://en.wikipedia.org/wiki/Link-local_address).
I believe you need to use a public IP service to identify yours (http://www.whatismyip.com/) and potentially use some kind of open source service for discovery.

If we wanted to list them all for it to work on any case, we should add those found in the following link: http://en.wikipedia.org/wiki/Reserved_IP_addresses#Reserved_IPv4_addresses

**Comment by BinaryConstruct** [comment]
It is defiantly a corner case, I wouldn't even have run into this if I hadn't accidentally disconnected from my wireless network. If you were on a private address it is unlikely you would be trying to create a multi-player session. Perhaps this should be handled by the application, such as a check for connectivity before adding the sessionmanager?

**Comment by Indiefreaks** [comment]
Well, since it is a pretty common scenario, I believe we should at least throw a warning that the game developer could catch up.

**Comment by dbacher** [comment]
var netAvail = System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable();

If only loopback and tunnel adapters are available, netAvail will be false.
If at least one real network connection is in the "up" state, netAvail will be true.
In Airplane mode, it ought to be false unless you've got Ethernet plugged in -- I'd have to test it, but that's probably a better test than the auto-configure IP address range.

Not tried it on a 360, but on a desktop you can register to receive network change notifications and it will tell you when the network changes states, which in turn can be used to do things like disable multiplayer features or pro-actively terminate a session without waiting for a time out.
