### ISSUE TITLE
Lidgren session crash on SendLocalPlayersToServer on serverside upon client connection

### ISSUE THREAD

**Issue by BinaryConstruct** [Indiefreaks/igf#7]
There seems to be some packet processing logic that may not be handled quite right.

Exception at LidgrenSession.Server.cs line 322 because _remotePlayerIpEndPoints is empty.
https://github.com/Indiefreaks/igf/blob/master/source/Indiefreaks.Game.Lidgren/Sessions/Lidgren/LidgrenSession.Client.cs#L322

**Comment by Indiefreaks** [comment]
I believe we just need to tweak AddNewPlayersOnServer on the same file (Line 262):

``` csharp
// we retrieve the player sent by the client                
var player = new LidgrenIdentifiedPlayer(_incomingMessage.ReadString())                                
{
       DisplayName = _incomingMessage.ReadString(),
};
_remotePlayerIpEndPoints.Add(player, incomingMessage.SenderEndPoint );
```

We would need to double check that...

**Comment by BinaryConstruct** [comment]
I think I have these worked out now with the latest batch of commits 0020fc317ee4712a401691c5a69c806d061cb173. Still need to work out joining in-progress sessions for lidgren and a few other issues but this will connect in my tests.
